### PR TITLE
Upgraded example for latest cypress and @percy/cypress 3.1.2

### PR DESCRIPTION
**Pull request by wi-ry**

### CODE REVIEW

**Comment by wi-ry** [comment]
@Robdel12 Can you please take a look at this?

**Comment by wi-ry** [comment]
@chinmay-browserstack or @shantanuk-browserstack ?

**Comment by willryan-stemcell** [comment]
@bstack-security-github

**Comment by ninadbstack** [comment]
@willryan-stemcell thanks for the pr, i will take a look at it today.

**Review by ninadbstack — APPROVED** [review]
Looks good, updated PR title!
Thanks @MrAusnadian for the contribution!

**Pull request merged**
